### ISSUE TITLE
[Feature Request] Password validation rules configuration

### ISSUE THREAD

**Issue by maksii** [andrii-kryvoviaz/slink#17]
Currently, the password-setting rules need to be more straightforward and more friendly. There is no indication besides a short error.
Moreover, the rule is based on the number of characters rather than their quality.

Example password:
1qaz@Wsx#Edc - number, low-uppercase, specials - NOT VALID, less than 16chars
1qaz2wsx3edc4rfv - number, lowercase only - VALID, 16chars

Suggested changes:
Add a docker environment variable that can overwrite the character count requirement, eg, set it to x chars (or, allow the user to change it from the profile page with lower standards).
Add a validation error message that will specify what exactly is wrong with the password.
Adjust rules to something like:

- At least 8 characters long
- Contains numbers
- Contains both lowercase and uppercase letters
- Includes special characters (e.g., @, #, $)

**Comment by andrii-kryvoviaz** [comment]
Certaenly, that's what I was going to change anyway.

As of now it uses this Symfony `PasswordStrenght` constraint, which is not that straightforward on how to configure the complexity:
```php
#[Assert\PasswordStrength(minScore: Assert\PasswordStrength::STRENGTH_MEDIUM)]
private string $password
```
More information here: [https://symfony.com/doc/current/reference/constraints/PasswordStrength.html](https://symfony.com/doc/current/reference/constraints/PasswordStrength.html)

I will just introduce a custom constraint, since the Symfony option is too general and oversimplified in terms of configuration.

**Comment by andrii-kryvoviaz** [comment]
Two ENV variables, `USER_PASSWORD_MIN_LENGTH` and `USER_PASSWORD_REQUIREMENTS`, have been introduced (47afe3d). 
These changes are included in the new release.

Password requirements are represented as a bitmask. I thought it would be ideal to consolidate all the flags under one parameter. Once Slink has an admin panel, it will be easier to adjust these settings.

Here are some options for the bitmask:
- `1`  - contains numbers
- `2` - contains lowercase letters
- `4` - contains uppercase letters
- `8` - contains special characters

Default values are:
`USER_PASSWORD_MIN_LENGTH` = 6
`USER_PASSWORD_REQUIREMENTS` = 15
