### ISSUE TITLE
Animated GIF support?

### ISSUE THREAD

**Issue by thecoffeebin** [andrii-kryvoviaz/slink#30]
I've spinned up a docker with latest image and realized that animated GIFs are uploaded as still images.

Is it an expected behavior or any configuration to change that?

**Comment by andrii-kryvoviaz** [comment]
No, it is not an expected behavior. I will introduce the fix with the upcoming release soon.

As a temporary solution, you can set `IMAGE_STRIP_EXIF_METADATA` to `false` if you don't use that feature much. Apparently, it attempts to remove metadata from GIF files as well. The downside is that you will need to reupload the GIFs since the original ones have already been modified.

**Comment by thecoffeebin** [comment]
@andrii-kryvoviaz It works (by setting IMAGE_STRIP_EXIF_METADATA=false). Thanks!! :)

**Comment by thecoffeebin** [comment]
While we're at it, I managed to upload an animated image with extension .webp but in my Upload History the thumbnail is not displayed with image type webp. Can you also fix it as well?

**Comment by andrii-kryvoviaz** [comment]
Sure. I just found that the underlying library doesn’t support cropping of animated images. I will introduce a quick fix to address this issue in the next release, and later, I might rewrite the cropping functionality from scratch.

**Comment by andrii-kryvoviaz** [comment]
Since [v1.3.0](https://github.com/andrii-kryvoviaz/slink/releases/tag/v1.3.0), enhanced support for animated images has been introduced. I just wanted to note, that it might affect the overall performance if many images are added at once, as each frame of an image is processed separately. As of now, caching is in place to mitigate the impact of it. If it becomes of a problem, I will consider adding GPU acceleration option for the docker container.
