### ISSUE TITLE
[ Feature Request ] Add ENV flag to customize upload size limit. 

### ISSUE THREAD

**Issue by arpanghosh8453** [andrii-kryvoviaz/slink#6]
Currently, users cannot upload files larger than 5 MB and that is not customizable. Is it possible to add an ENV flag for this so we can customize that when spinning up the docker container?

**Comment by andrii-kryvoviaz** [comment]
That what I was thinking too. Should be definitaly included somewhere in the next builds.

**Comment by arpanghosh8453** [comment]
Perfect! Thank you again for considering my ideas :)

**Comment by andrii-kryvoviaz** [comment]
Added support for configurable upload size in cceb639 and will be a part of the next release.

The only thing, it will still have a hard limit, which is determined by PHP configuration (currently 50M). It is assiged at the image building step. Theoretically, new configuration files could be mounted onto a container, to overcome the limit, but I don't think that someone will need to do so, since 50M is enough for 99% cases.

I could possibly make a bash script wich will update the configuration based on the ENV variables on container start, but this will overcomplecate things, as I will sooner or later make all the settings configurable form the web interface as well.
